### ISSUE TITLE
ATF framework is not able to identify Resource

### ISSUE THREAD

**Issue by FennyR** [google/Accessibility-Test-Framework-for-Android#17] opened 2019-12-26 18:31 UTC
I am this ATF framework in my project. With library, I am able to successfully identify the Accessibiliy violation. But after identifying the violation, the code is trying to return the link with violation details. Here at this step, the library is failing and giving Resource Not Found exception for any language selected. I am attaching the exception below. Please look into it and respond.

java.util.MissingResourceException: Can't find bundle for base name com.google.android.apps.common.testing.accessibility.framework.strings, locale en
2019-12-26 12:25:32.595 11773-11773/com.example.systemoverlaydemo W/System.err:     at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1558)
2019-12-26 12:25:32.595 11773-11773/com.example.systemoverlaydemo W/System.err:     at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1381)
2019-12-26 12:25:32.595 11773-11773/com.example.systemoverlaydemo W/System.err:     at java.util.ResourceBundle.getBundle(ResourceBundle.java:1300)
2019-12-26 12:25:32.595 11773-11773/com.example.systemoverlaydemo W/System.err:     at com.google.android.apps.common.testing.accessibility.framework.strings.StringManager.getResourceBundle(StringManager.java:33)
2019-12-26 12:25:32.595 11773-11773/com.example.systemoverlaydemo W/System.err:     at com.google.android.apps.common.testing.accessibility.framework.strings.StringManager.getString(StringManager.java:27)
2019-12-26 12:25:32.595 11773-11773/com.example.systemoverlaydemo W/System.err:     at com.google.android.apps.common.testing.accessibility.framework.checks.SpeakableTextPresentCheck.generateMessageForResultId(SpeakableTextPresentCheck.java:148)
2019-12-26 12:25:32.595 11773-11773/com.example.systemoverlaydemo W/System.err:     at com.google.android.apps.common.testing.accessibility.framework.checks.SpeakableTextPresentCheck.getMessageForResultData(SpeakableTextPresentCheck.java:125)
2019-12-26 12:25:32.595 11773-11773/com.example.systemoverlaydemo W/System.err:     at com.google.android.apps.common.testing.accessibility.framework.AccessibilityHierarchyCheck.getMessageForResult(AccessibilityHierarchyCheck.java:74)
2019-12-26 12:25:32.595 11773-11773/com.example.systemoverlaydemo W/System.err:     at com.google.android.apps.common.testing.accessibility.framework.AccessibilityHierarchyCheckResult.getRawMessage(AccessibilityHierarchyCheckResult.java:129)
2019-12-26 12:25:32.595 11773-11773/com.example.systemoverlaydemo W/System.err:     at com.google.android.apps.common.testing.accessibility.framework.AccessibilityHierarchyCheckResult.getMessage(AccessibilityHierarchyCheckResult.java:143)
2019-12-26 12:25:32.595 11773-11773/com.example.systemoverlaydemo W/System.err:     at service.FloatingCircle.onAccessibilityEvent(FloatingCircle.java:442)
2019-12-26 12:25:32.595 11773-11773/com.example.systemoverlaydemo W/System.err:     at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1561)
2019-12-26 12:25:32.595 11773-11773/com.example.systemoverlaydemo W/System.err:     at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1747)

**Exception**: "java.util.MissingResourceException: Can't find bundle for base name com.google.android.apps.common.testing.accessibility.framework.strings, locale en
2019-12-26 12:25:32.595 11773-11773/com.example.systemoverlaydemo W/System.err:     at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1558)"

facing the same exception of any language selection.

**Comment by caseyburkhardt** [comment] 2020-02-15 06:56
We've made a number of changes around string management and translation in our latest v3.1 release, which was just [merged](https://github.com/google/Accessibility-Test-Framework-for-Android/pull/18) to master.  Please sync the latest source and please let us know if you're still running into issues here.

**Comment by sunyal** [comment] 2020-03-18 13:53
I'm hitting this as well. Is there a fix coming for this or a workaround?

**Comment by sunyal** [comment] 2020-03-18 14:18
This is also happening for me. I am unable to get this to work in the Robolectric environment.

**Comment by sunyal** [comment] 2020-03-18 14:39
Also happening in the androidTest Espresso tests

**Comment by FennyR** [comment] 2020-03-18 14:44
Hi Casey,

 I am facing issues with the latest version. The app is crashing the moment
I am scanning a screen for accessibility violation checks. I shall upload
the error log shortly.

Thanks,
Fenny R.

**Comment by caseyburkhardt** [comment] 2020-03-18 15:08
Thanks for the update @FennyR and @sunyal.  Updated logs appreciated, and I'll start looking into repro'ing this today.

**Comment by zakharchanka** [comment] 2020-04-09 13:06
Hello. Any news?

**Comment by danAharoni2** [comment] 2020-05-06 16:06
@caseyburkhardt 
I'm getting the same error with v3.0 as well.

**Comment by caseyburkhardt** [comment] 2020-10-05 20:58
Thanks for bearing with us on this.  We've revised our approach to packaging resources, which gets a bit complicated with a few of our internal release variants of the library.  This should now be resolved with the latest push.

**Comment by ekimmel-ta** [comment] 2021-01-06 22:03
I am still receiving this exception in 3.1.  This is coming from a test using ParameterizedRobolectricTestRunner.  If you would rather me open a new issue, let me know.

```
    java.util.MissingResourceException: Can't find bundle for base name .strings, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:1308)
        at com.google.android.apps.common.testing.accessibility.framework.strings.StringManager.getResourceBundle(StringManager.java:63)
        at com.google.android.apps.common.testing.accessibility.framework.strings.StringManager.getString(StringManager.java:42)
        at com.google.android.apps.common.testing.accessibility.framework.checks.RedundantDescriptionCheck.checkForWords(RedundantDescriptionCheck.java:185)
        at com.google.android.apps.common.testing.accessibility.framework.checks.RedundantDescriptionCheck.runCheckOnHierarchy(RedundantDescriptionCheck.java:158)
        at com.google.android.apps.common.testing.accessibility.framework.AccessibilityViewHierarchyCheck.runDelegationCheckOnView(AccessibilityViewHierarchyCheck.java:101)
        at com.google.android.apps.common.testing.accessibility.framework.RedundantContentDescViewCheck.runCheckOnViewHierarchy(RedundantContentDescViewCheck.java:38)
        at com.google.android.apps.common.testing.accessibility.framework.integrations.espresso.AccessibilityValidator.runAccessibilityChecks(AccessibilityValidator.java:225)
        at com.google.android.apps.common.testing.accessibility.framework.integrations.espresso.AccessibilityValidator.checkAndReturnResults(AccessibilityValidator.java:87)
        at androidx.test.espresso.accessibility.AccessibilityChecks$2.check(AccessibilityChecks.java:65)
```

**Comment by caseyburkhardt** [comment] 2021-01-07 17:00
Reopening for some additional investigation, although we were unable to reproduce this when we were validating the 3.1 release candidate.

@ekimmel-ta Can you clarify if you're building the project from source, or from our Maven artifact?  Any other information to help is reproduce this is appreciated.

**Comment by ekimmel-ta** [comment] 2021-01-07 18:38
This is pulling down the 3.1 maven artifact. I am using Espresso 3.3.0, and forcing the ATF resolution to be 3.1 while waiting for that team to [merge the update](https://github.com/android/android-test/pull/834) officially. 

I will work on reproducing the issue in a sample project.

**Comment by ekimmel-ta** [comment] 2021-01-07 19:25
Here is a minimal example showcasing the exception. https://github.com/ekimmel-ta/ATFSample

**Comment by CooperCorona** [comment] 2021-01-14 19:30
Hi ekimmel-ta,

Sorry for the delay. After much debugging, I think we've identified the issue. Gradle is not packaging files in the `assets/` directory into unit tests. It packages them fine in the application process or Espresso tests. I think we can fix this by using the Java-style `resources/` directory, instead. Working on the fix now; I'll update the issue when it's out, and we can see if that fixes your sample.

**Closed** 2021-02-03 05:14 UTC

**Comment by CooperCorona** [comment] 2021-02-03 23:24
Hi ekimmel-ta,

We just pushed a new version to Maven. Can you try pulling `3.1.1` and see if it works?

**Comment by ekimmel-ta** [comment] 2021-02-04 18:33
Hello! I've pulled in the latest version. 

Some behavior seems to have changed between v2 and v3 regarding the root view being tested for accessibility, even if it doesn't match the "suppressing result matcher".  After marking some of the scaffolding of our test layout as not important for accessibility, the tests do indeed succeed!  Thank you for the patch!

**Comment by caseyburkhardt** [comment] 2021-02-04 20:14
Some behavior changes are expected between versions of ATF, as we roll out new accessibility checks, fix bugs, and (hopefully) introduce fewer new bugs.

If you suspect the results you're receiving are not accurate, please do open a separate issue with a minimal repro example of your layout, and we'd be more than happy to take a look.

**Comment by JadeByfield89** [comment] 2021-07-20 16:23
Hello, I'm still running into this issue on version 3.4.0 of the [Espresso Accessibility testing library](https://mvnrepository.com/artifact/androidx.test.espresso/espresso-accessibility?repo=google). Is there a fix for this issue, or should we be using a specific version?
