### ISSUE TITLE
3.1 regression

### ISSUE THREAD

**Issue by ZacSweers** [google/Accessibility-Test-Framework-for-Android#19] opened 2020-02-17 22:37 UTC
Took an early local build of master with the upcoming 3.1 changes, and unfortunately seems it's regressed for us.

```
java.util.MissingResourceException
at java.util.ResourceBundle.getBundle(ResourceBundle.java:327)
at com.google.android.apps.common.testing.accessibility.framework.strings.StringManager.getResourceBundle(StringManager.java:32)
at com.google.android.apps.common.testing.accessibility.framework.strings.StringManager.getString(StringManager.java:27)
at com.google.android.apps.common.testing.accessibility.framework.checks.RedundantDescriptionCheck.runCheckOnHierarchy(RedundantDescriptionCheck.java:128)
at com.google.android.apps.common.testing.accessibility.framework.AccessibilityViewHierarchyCheck.runDelegationCheckOnView(AccessibilityViewHierarchyCheck.java:101)
at com.google.android.apps.common.testing.accessibility.framework.RedundantContentDescViewCheck.runCheckOnViewHierarchy(RedundantContentDescViewCheck.java:38)
at com.google.android.apps.common.testing.accessibility.framework.integrations.espresso.AccessibilityValidator.runAccessibilityChecks(AccessibilityValidator.java:204)
at com.google.android.apps.common.testing.accessibility.framework.integrations.espresso.AccessibilityValidator.checkAndReturnResults(AccessibilityValidator.java:82)
at androidx.test.espresso.accessibility.AccessibilityChecks$2.check(AccessibilityChecks.java:65)
at androidx.test.espresso.action.ViewActions$1.perform(ViewActions.java:130)
at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:366)
at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:255)
at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:65)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:158)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:155)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by ZacSweers** [comment] 2020-02-18 18:50
Here's a fuller trace

```
java.util.MissingResourceException: Can't find bundle for base name com.google.android.apps.common.testing.accessibility.framework.strings, locale en_US
at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1561)
at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1384)
at java.util.ResourceBundle.getBundle(ResourceBundle.java:1293)
at com.google.android.apps.common.testing.accessibility.framework.strings.StringManager.getResourceBundle(StringManager.java:32)
at com.google.android.apps.common.testing.accessibility.framework.strings.StringManager.getString(StringManager.java:27)
at com.google.android.apps.common.testing.accessibility.framework.checks.RedundantDescriptionCheck.runCheckOnHierarchy(RedundantDescriptionCheck.java:128)
at com.google.android.apps.common.testing.accessibility.framework.AccessibilityViewHierarchyCheck.runDelegationCheckOnView(AccessibilityViewHierarchyCheck.java:101)
at com.google.android.apps.common.testing.accessibility.framework.RedundantContentDescViewCheck.runCheckOnViewHierarchy(RedundantContentDescViewCheck.java:38)
at com.google.android.apps.common.testing.accessibility.framework.integrations.espresso.AccessibilityValidator.runAccessibilityChecks(AccessibilityValidator.java:204)
at com.google.android.apps.common.testing.accessibility.framework.integrations.espresso.AccessibilityValidator.checkAndReturnResults(AccessibilityValidator.java:82)
at androidx.test.espresso.accessibility.AccessibilityChecks$2.check(AccessibilityChecks.java:65)
at androidx.test.espresso.action.ViewActions$1.perform(ViewActions.java:130)
at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:366)
at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:255)
at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:65)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:158)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:155)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by caseyburkhardt** [comment] 2020-03-18 17:01
Thanks for the report. This looks like a dupe of Issue #17.  Let's centralize discussion there.

**Closed by caseyburkhardt** 2020-03-18 17:01 UTC
